plugin_dirs = [
    '/home/jj/.wine/drive_c/Program Files/Ample Sound',
    '/home/jj/.wine/drive_c/Program Files/Common Files/Steinberg/VST2',
    '/home/jj/.wine/drive_c/Program Files/Common Files/VST2',
    '/home/jj/.wine/drive_c/Program Files/Common Files/VST3',
    '/home/jj/.wine/drive_c/Program Files/Steinberg/VSTPlugins',
    '/home/jj/.wine/drive_c/Program Files/Vstplugins',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-7.20'
yabridge_host_hash = -3094479323878875900
